name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.8.0
  SQLX_FEATURES: "rustls,postgres"
  APP_USER: app
  APP_USER_PWD: secret
  APP_DB_NAME: newsletter
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: install sqlx-cli
        run: cargo install sql-cli
          --version=${{ env.SQLX_VERSION }}
          --features=${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - name: create app user in postgres
        run: |
          sudo apt-get install postgresql-client
          CREATE_QUERY="CREATE USER ${APP_USER} WITH PASSWORD '${APP_USER_PWD}';"
          PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${CREATE_QUERY}"
          GRANT_QUERY="ALTER USER ${APP_USER} CREATEDB;"
          PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${GRANT_QUERY}"
      - name: migrate database
        run: SKIP_DOCKER=true ./scripts/init_db.sh
      - name: run tests
        run: cargo test --verbose
      - name: check that queries are fresh
        run: cargo sqlx prepare --workspace --check -- --all-targets
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run lint
      run: cargo clippy -- -D warnings
    - name: Run formatting
      run: cargo fmt -- --check
    - name: Run audit
      run: cargo install cargo-audit && cargo audit
